"""Add ContactSubmission

Revision ID: 182734a9fe7b
Revises: 0004_project_owner
Create Date: 2026-06-27 17:40:17.044465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '182734a9fe7b'
down_revision: Union[str, None] = '0004_project_owner'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlist')
    op.drop_index('user_queries_created_idx', table_name='user_queries')
    op.drop_index('user_queries_kind_idx', table_name='user_queries')
    op.drop_index('user_queries_status_idx', table_name='user_queries')
    op.drop_index('user_queries_user_idx', table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_table('profiles')
    op.alter_column('agent_runs', 'scan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('monitoring_runs', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('page_snapshots', 'scan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('prompts', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('prompts', 'intent',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'custom'::character varying"))
    op.drop_constraint('prompts_project_id_fkey', 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recommendations', 'scan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('scans', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('visibility_checks', 'run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('visibility_checks', 'prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visibility_checks', 'prompt_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('visibility_checks', 'run_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('scans', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('recommendations', 'scan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.create_foreign_key('prompts_project_id_fkey', 'prompts', 'projects', ['project_id'], ['id'])
    op.alter_column('prompts', 'intent',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'custom'::character varying"))
    op.alter_column('prompts', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('page_snapshots', 'scan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('monitoring_runs', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('agent_runs', 'scan_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'user'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='profiles_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey'),
    comment='One row per authenticated user. The user list.'
    )
    op.create_table('user_queries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.TEXT(), server_default=sa.text("'query'::text"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("kind = ANY (ARRAY['query'::text, 'chat'::text, 'feedback'::text, 'bug'::text, 'feature_request'::text, 'support'::text])", name='user_queries_kind_check'),
    sa.CheckConstraint("status = ANY (ARRAY['new'::text, 'reviewed'::text, 'in_progress'::text, 'resolved'::text, 'archived'::text])", name='user_queries_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='user_queries_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='user_queries_pkey'),
    comment='Every user query/feedback — review to improve the product.'
    )
    op.create_index('user_queries_user_idx', 'user_queries', ['user_id'], unique=False)
    op.create_index('user_queries_status_idx', 'user_queries', ['status'], unique=False)
    op.create_index('user_queries_kind_idx', 'user_queries', ['kind'], unique=False)
    op.create_index('user_queries_created_idx', 'user_queries', [sa.text('created_at DESC')], unique=False)
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waitlist_pkey'),
    sa.UniqueConstraint('email', name='waitlist_email_key')
    )
    # ### end Alembic commands ###
